local Stack = require("Stack")

s = Stack:new()
print(s:isEmpty())
s:push(1)
s:push(2)
s:push(3)
s:push(4)
print(s:isEmpty())
print(s:top())
print(s[4])
print(s:pop())
print(s:pop())
print(s:pop())
print(s:pop())
print(s:pop())
print(s:isEmpty())